Update the Ollama model hosting details with more clarity
ibm-granite-community/utils pull request #14
Opened 2024-10-01 08:36 UTC by hickeyma

Added information on installing and running the Ollam server. The information is necessary for users when using Ollama in a notebook.

2024-10-01 13:12 UTC, fayvor commented
Thanks, @hickeyma. Could you instead link to the [Ollama Getting Started instructions](https://github.com/ibm-granite-community/utils/blob/main/recipes/Getting_Started/Getting_Started_with_Ollama.ipynb) and make sure those are complete?

2024-10-01 13:41 UTC, bjhargrave commented on recipes/Components/Langchain_LLMs.ipynb
> +    "2. Start the Ollama server\n",
I think you need step 3: `!ollama pull granite-code:3b` to download a model.

2024-10-01 15:55 UTC, hickeyma commented
> These instructions are missing the proper pip install command for the langchain_ollama package.

@bjhargrave Could you describe more what is missing? Sorry not sure what you are asking.

2024-10-01 19:09 UTC, bjhargrave commented
> Could you describe more what is missing? Sorry not sure what you are asking.

<img width="993" alt="Screenshot 2024-10-01 at 15 06 26" src="https://github.com/user-attachments/assets/f93fe92c-407b-4aa6-a662-21a118232278">

The langchain_ollama package is not present. No prior step in the notebook pip installs the necessary packages. Without a step to install the package, the `from` statement fails.

2024-10-01 19:25 UTC, rawkintrevo commented
Iirc, the recipes in this repo are being moved to `snacks` or `kitchen`. @fayvor or @adampingel can comment more.

2024-10-01 20:19 UTC, fayvor requested changes

2024-10-01 20:19 UTC, fayvor commented on recipes/Getting_Started/Getting_Started_with_Ollama.ipynb
> +   ]
I don't think we need this again, do we?

2024-10-01 20:19 UTC, fayvor commented on recipes/Getting_Started/Getting_Started_with_Ollama.ipynb
> +    "!ollama pull granite-code:20b"
Agreed, the user might as well download these three. Should we also include 34B?

2024-10-01 20:19 UTC, fayvor commented on recipes/Getting_Started/Getting_Started_with_Ollama.ipynb
> -    "IBM Granite Code models available on Ollama can be found [here](https://ollama.com/library/granite-code).\n",
Could we keep this link? New models will arrive on Ollama.

2024-10-01 20:19 UTC, fayvor commented on recipes/Getting_Started/Getting_Started_with_Ollama.ipynb
> +    "The Ollama server can be run locally on your system or in the notebook itself.\n",
Both methods run the server locally (on the same host as the notebook). Maybe "from a terminal" or "from the notebook"?

2024-10-01 20:19 UTC, fayvor commented on recipes/Getting_Started/Getting_Started_with_Ollama.ipynb
> +    "    ```"
I like the refactoring you've done here: putting the full instructions under each option.

2024-10-01 20:22 UTC, fayvor commented
> The langchain_ollama package is not present. No prior step in the notebook pip installs the necessary packages.

@bjhargrave I see that. I can fix it when I move these recipes to the Kitchen, if it hasn't been fixed here.

2024-10-03 13:19 UTC, fayvor commented
@hickeyma I've moved these changes to a [new PR](https://github.com/ibm-granite-community/granite-kitchen/pull/4) against `granite-kitchen`, where these recipes are migrating. Please review there.

2024-10-03 18:20 UTC, fayvor commented
See [this PR](https://github.com/ibm-granite-community/granite-kitchen/pull/4).

2024-10-03 18:20 UTC, closed without merging